### ISSUE TITLE
有设计文档吗？

### ISSUE THREAD

**Issue by zhaofeng555** [leopardoooo/easyooo-framework#1]
您好，我对这个项目很感兴趣，你有一些设计文档什么的吗？如果需要的话，我也可以加入这个开发，本人6年java高程。QQ：443842006

**Comment by leopardoooo** [comment]
@zhaofeng555  你好，很抱歉，之前一直忙于项目，没有关注github，这个项目目前处于开发阶段，文档是比较欠缺的，后期我会补上相关的文档，同时也很愿意你能参与到这个项目！
