### ISSUE TITLE
代码好像没提交全

### ISSUE THREAD

**Issue by ipandage** [leopardoooo/easyooo-framework#2]
SimpleService 有编译错误

**Comment by leopardoooo** [comment]
@ipandage 很感谢您的关注，您出现的问题我表示很抱歉，该项目已经有一段时间没有维护了，但有线上的项目正在使用，目前较稳定，

**Comment by leopardoooo** [comment]
@ipandage 很感谢您的关注，您出现的问题我表示很抱歉，编译错误中,我已修正并push，你pull一次即可。

该项目已经有一段时间没有维护了，但线上的项目使用较稳定。如果您是出于学习目的可以看看，但我不太建议您使用于项目中，因为它是一个集成性的项目，在使用的过程中有可能会出现一些莫名其妙的错误，如果对源代码不是很熟悉，可能会影响到你们项目进度。 

—————

另外：您所参考的SimpleService是一个DEMO，可能运行不起来，因为它还需要依赖一些环境比如数据库，redis，表结构等。有时间我会把DEMO完全独立出去，做一个完整的DEMO，包括SQL文件等。
